# Generated by Django 3.2 on 2022-06-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='qunantity',
            new_name='quantity',
        ),
    ]
